<!doctype html><html lang="<?= Visao::escapar($idioma) ?>"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aceitar convite | Prospera</title><link rel="icon" href="assets/images/favicon-wx.svg" type="image/svg+xml"><link rel="stylesheet" href="css/style.css?v=6"></head>
<body class="pagina-login"><main class="cartao-login cartao-convite"><div class="brand marca-login"><span class="brand-mark">↑</span>Prospera</div>
<?php if(!$convite): ?><h1>Convite indisponível</h1><p>Este convite expirou, já foi utilizado ou não é válido.</p><a class="btn btn-primary" href="?pagina=login">Voltar ao login</a>
<?php else: ?><span class="eyebrow">Você foi convidado</span><h1>Crie seu acesso</h1><p>Preencha seus próprios dados. Quem convidou você não verá sua renda, empresa ou senha.</p>
<?php if($erro):?><div class="mensagem-erro" role="alert"><?= Visao::escapar($erro) ?></div><?php endif;?>
<form method="post" class="formulario-login formulario-aceitar-convite"><input type="hidden" name="token" value="<?= Visao::escapar($token) ?>"><input type="hidden" name="acao" value="aceitar_convite"><input type="hidden" name="credencial" value="<?= Visao::escapar($credencial) ?>">
<label>Nome completo<input name="nome" required maxlength="100" autocomplete="name"></label><label>Apelido público<input name="apelido" required maxlength="40" placeholder="Nome exibido no ranking"></label><label>E-mail<input type="email" name="email" required autocomplete="email"></label><label>Senha<input type="password" name="senha" required minlength="8" autocomplete="new-password"></label><label>Confirmar senha<input type="password" name="senha_confirmacao" required minlength="8" autocomplete="new-password"></label>
<div class="caixa-lgpd"><strong>Privacidade</strong><p>Usaremos os dados para criar e proteger sua conta, calcular seu planejamento e manter a rede de convites. Dados financeiros não aparecem no ranking.</p></div><label class="check"><input type="checkbox" name="aceite_privacidade" value="1" required><span>Li e estou ciente do uso dos meus dados para essas finalidades.</span></label><button class="btn btn-primary">Criar minha conta</button></form>
<?php endif; ?></main></body></html>
